/** @format */

// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  activeItem: string
  'close-btn': string
  'list-content': string
  'list-header': string
  'music-item': string
  'music-list': string
  'music-name': string
  'operate-area': string
  'operate-btn': string
  'tab-group': string
  'top-tab': string
}
declare var cssExports: CssExports
export = cssExports
