// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon-close': string;
  'icon-email': string;
  'icon-lockclosed': string;
  'icon-reduce': string;
  'icon-setting': string;
  'icon-zuidahua': string;
  'icon-zuidahua1': string;
  'iconfont': string;
}
declare var cssExports: CssExports;
export = cssExports;
