/** @format */

// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card-content': string
  'card-header': string
  'card-opter': string
  'card-title': string
  'miko-card': string
}
declare var cssExports: CssExports
export = cssExports
