/** @format */

// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'change-control': string
  'control-item': string
  'player-controller': string
  progress: string
  'progress-control': string
  time: string
  totalTime: string
  'volume-control': string
}
declare var cssExports: CssExports
export = cssExports
