/** @format */

// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-footer': string
  'music-list-total': string
  'music-player-controller': string
  'total-num': string
}
declare var cssExports: CssExports
export = cssExports
