/** @format */

// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active-item': string
  'group-title': string
  'left-aside': string
  'menu-content': string
  'menu-item': string
  'menu-item-normal': string
}
declare var cssExports: CssExports
export = cssExports
