// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'top-nav': string;
  'window-operate': string;
}
declare var cssExports: CssExports;
export = cssExports;
