// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'css1': string;
  'css2': string;
  'css3': string;
  'css4': string;
  'css5': string;
}
declare var cssExports: CssExports;
export = cssExports;
