// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'scss1': string;
  'scss2': string;
  'scss3': string;
  'scss4': string;
}
declare var cssExports: CssExports;
export = cssExports;
