// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'less1': string;
  'less2': string;
  'less3': string;
  'less4': string;
}
declare var cssExports: CssExports;
export = cssExports;
