/** @format */

// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  footer: string
  header: string
  'left-aside': string
  'main-content': string
}
declare var cssExports: CssExports
export = cssExports
