/** @format */

// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  btn: string
  'play-btn': string
}
declare var cssExports: CssExports
export = cssExports
