/** @format */

// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  banners: string
  'color-333': string
  'color-888': string
  'exclusive-item-name': string
  'exclusive-list': string
  'exclusive-list-item': string
  'fm-item-img-box': string
  'fm-item-name': string
  'fm-list': string
  'fm-list-item': string
  'item-box': string
  'item-copywriter': string
  'item-img-box': string
  'item-name': string
  'item-play-btn': string
  'item-right-top': string
  'latest-item-img-box': string
  'latest-list': string
  'latest-list-group': string
  'latest-list-item': string
  'latest-play-btn': string
  'mv-item-img-box': string
  'mv-item-name': string
  'mv-list': string
  'mv-list-item': string
  'play-list-item': string
  'recommended-play-list': string
  special: string
}
declare var cssExports: CssExports
export = cssExports
